### ISSUE TITLE
search causing CORS error on deployed version

### ISSUE THREAD

**Issue by samtous** [Kallirroi/wordsinspace#84] opened 2020-08-18 16:13 UTC
<img width="1552" alt="Screen Shot 2020-08-18 at 12 11 27" src="https://user-images.githubusercontent.com/5625731/90538162-2bfd3500-e14c-11ea-996a-595ac31648bd.png">

**Comment by samtous** [comment] 2020-08-18 16:13
I checked and the urls in gatsby-config and wrap-page-element match fine

**Comment by Kallirroi** [comment] 2020-08-19 22:36
Hm thats pretty annoying, and pretty sure its because of URL migration. Can we edit the .htaccess file to allow it?

**Comment by Kallirroi** [comment] 2020-08-19 22:36
actually I take that back, I should probably look into Apollo config props first. Since its search, its internal CORS. Sigh.

**Comment by samtous** [comment] 2020-08-19 23:03
yeah afraid this was pre doing anything with the URL migration, though there's chance it has to do with redirects? It seems to work fine locally

**Comment by Kallirroi** [comment] 2020-08-20 15:27
cant reproduce, so closing for now - this is relevant in case it happens again: https://github.com/apollographql/apollo-client/issues/5764#issuecomment-574930001

**Closed by Kallirroi** 2020-08-20 15:27 UTC
Labels: bug
